rm src\stm32f1adc.c 
rm src\stm32f1dma.c 
rm src\stm32f1gpio.c
rm src\stm32f1i2c.c 
rm src\stm32f1spi.c 
rm src\stm32f1tim.c 
rm src\current.cpp
rm src\i2cx.cpp
rm src\spix.cpp
rm src\lcd.cpp
rm src\stm32Info.cpp

rm include\adc.h
rm include\current.h
rm include\dma.h
rm include\gpio.h
rm include\i2c.h
rm include\main.h
rm include\spi.h
rm include\tim.h
rm include\cyclectr.h
rm include\stm32Info.h
